# Generated by Django 5.0.4 on 2024-04-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('data_de_nascimento', models.DateField()),
                ('cargo', models.CharField(max_length=100)),
                ('salario', models.IntegerField()),
                ('data_de_admissao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
